# Generated by Django 3.1.7 on 2021-04-03 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_name', models.CharField(max_length=128)),
                ('mail_adresse', models.EmailField(max_length=512)),
                ('mdp', models.CharField(max_length=512)),
                ('key1', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=512)),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('proprio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendrier.utilisateur')),
            ],
        ),
    ]
