# Generated by Django 3.1.7 on 2021-04-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='color',
            field=models.IntegerField(default=5),
        ),
    ]
