# Generated by Django 3.1.7 on 2021-04-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_evenement_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cle2',
            field=models.CharField(default='empty', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='cle',
            field=models.CharField(max_length=64),
        ),
    ]
