# Generated by Django 3.1.8 on 2021-05-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210430_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='calendar',
            field=models.CharField(default='Test calendar', max_length=1024),
            preserve_default=False,
        ),
    ]
