# Generated by Django 3.1.7 on 2021-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_evenement_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(default='ffc5e8048a29a59480ce17b0e2df39bf5b015720e1578f1fa2ba77c50063470d', max_length=512),
            preserve_default=False,
        ),
    ]
