# Generated by Django 3.1.7 on 2021-05-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='key',
            field=models.CharField(default='aaaaaaaaaa', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=32),
        ),
    ]
