# Generated by Django 3.1.7 on 2021-06-09 12:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210526_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cle',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cle2',
        ),
        migrations.AlterField(
            model_name='evenement',
            name='key',
            field=models.CharField(default=api.models.getEventCode, max_length=1024),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default=api.models.getCode, max_length=32),
        ),
    ]
