# Generated by Django 3.2.5 on 2021-08-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210807_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='recurence',
            field=models.IntegerField(default=-1),
        ),
    ]
