# Generated by Django 3.2.5 on 2021-08-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_evenement_recurence'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='recurenceEndNbr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evenement',
            name='recurenceEndType',
            field=models.IntegerField(default=1),
        ),
    ]
