# Generated by Django 3.2.5 on 2021-08-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210810_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='recurenceEndType',
            field=models.IntegerField(default=0),
        ),
    ]
