# Generated by Django 3.1.7 on 2021-04-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=512)),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('proprio', models.CharField(max_length=512)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=512, unique=True)),
                ('password', models.CharField(max_length=1024)),
                ('username', models.CharField(max_length=512, unique=True)),
                ('account_creation_date', models.DateTimeField(auto_now_add=True)),
                ('cle', models.CharField(max_length=1024)),
            ],
        ),
    ]
